/*Variable Values*/
php_image_name = "php-httpd:challenge"
mariadb_image_name = "mariadb:challenge"
network_name = "my_network"
php_container_name = "webserver"
common_labels = "second"
php_hostname = "php_httpd"
php_container_hostpath = "/root/code/terraform-challenges/challenge2/lamp_stack/website_content/"
php_container_containerpath = "/var/www/html"
dashboard_container_name = "db_dashboard"
dashboard_hostname = "phpmyadmin"
dashboard_image_name = "phpmyadmin/phpmyadmin"
mariadb_container_name = "db"
mariadb_hostname = "db"
mysql_root_password = "1234"
mysql_database_name = "simple-website"
mariadb_volume_name = "mariadb-volume"
mariadb_containerpath = "/var/lib/mysql"